spring.application.name=AIRecap
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=
gemini.api.key=${GEMINI_KEY}
server.port=${PORT:8081}
server.address=0.0.0.0